Bug fixes for failing unit tests when UID width is changed from the default 3 (specifically tested with 4)
The following tests failed as of 2.1.0:
  TestTimeSeriesLookup.tagkOnlyMeta:211 expected:<5> but was:<6>
  TestTimeSeriesLookup.tagkOnlyMetaStar:227 expected:<5> but was:<6>
  TestTimeSeriesLookup.tagkOnlyData:244 expected:<5> but was:<6>
  TestTimeSeriesLookup.tagkOnly2Meta:260 expected:<2> but was:<0>
  TestUniqueIdRpc.tsuidPostByM