Fix a bug in the downsampling code.
Any attempt to downsample a mix of integer values and floating values
would result in an Internal Server Error caused by:
  java.lang.ClassCastException: value #N is not a float in RowSeq(...)
  at net.opentsdb.core.RowSeq.doubleValue(RowSeq.java:288)
  at net.opentsdb.core.Span$DownsamplingIterator.nextDoubleValue(Span.java:508)
  at net.opentsdb.core.Aggregators$Avg.runDouble(Aggregators.java:169)
  at net.opentsdb.core.Span$DownsamplingIterator.next(Span.java:418)
  at net.opentsdb.core.SpanGroup$SGIterator.moveToNext(SpanGroup.java:604)
  [... in tsdb-1.0.jar as of 08a85bb]

Bug reported by Matthieu Tourne.

Change-Id: I6d3875ccf83b67369e0db068503ed910d97ef0f6